// Types describing chatbot conversations and the sources used for an answer.

export type ChatRole = 'user' | 'assistant';

/** A passage taken from an uploaded document that supported an answer. */
export interface Source {
  documentId: string;
  documentName: string;
  excerpt: string;
  pageNumber?: number;
}

export interface Message {
  id: string;
  role: ChatRole;
  content: string;
  sources: Source[];
  createdAt: string;
}

/** Payload sent to POST /api/chat/. */
export interface SendMessagePayload {
  /** chat_sessions id to continue; omit to start a new session. */
  sessionId?: string;
  content: string;
}

/** One message as returned by the API (Django/DRF snake_case). */
export interface ApiChatMessage {
  id: string;
  role: ChatRole;
  content: string;
  created_at: string;
}

/** One grounded source as returned by POST /api/chat/ (snake_case). */
export interface ApiSource {
  document_id: string;
  document_type: 'university' | 'student';
  document_name: string;
  page: number | null;
  section: string | null;
  score: number;
  excerpt: string;
}

/** Response body of POST /api/chat/. */
export interface SendChatResponse {
  session_id: string;
  session_title: string;
  /** Grounded answer generated by the agent (may be absent on error paths). */
  answer?: string;
  /** What the agent actually retrieved — never fabricated. */
  sources?: ApiSource[];
  messages: ApiChatMessage[];
}
