# Generated by Django 5.2.17 on 2026-09-26 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='session',
            field=models.ForeignKey(blank=True, help_text='Chat session the document was uploaded in.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='chatbot.chatsession'),
        ),
    ]
