# Generated by Django 5.2.17 on 2026-09-26 16:35

import django.db.models.deletion
import pgvector.django.vector
import uuid
from django.db import migrations, models
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_document_session'),
    ]

    operations = [
        # The `vector` extension must exist before the table that uses the
        # vector(384) column. VectorExtension is idempotent (checks
        # pg_extension first), so databases where it was enabled manually
        # migrate cleanly too.
        VectorExtension(),
        migrations.CreateModel(
            name='DocumentVector',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chunk_id', models.UUIDField(help_text='ProcessedChunk.chunk_id (same id as document_chunks.id).')),
                ('chunk_index', models.PositiveIntegerField()),
                ('document_type', models.CharField(blank=True, default='', help_text='Document.Source: "university" or "student" — lets retrieval filter by type.', max_length=20)),
                ('page', models.PositiveIntegerField(blank=True, help_text='Source page when the extractor could detect one.', null=True)),
                ('section', models.CharField(blank=True, default='', help_text='Section/heading the chunk came from (shown in citations).', max_length=255)),
                ('content', models.TextField(help_text='Chunk text, so retrieval can return it without a second lookup.')),
                ('embedding', pgvector.django.vector.VectorField(dimensions=384)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Processor metadata not promoted to a column.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vectors', to='chatbot.document')),
                ('session', models.ForeignKey(blank=True, help_text='Chat session the document was uploaded in (null for legacy documents).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vectors', to='chatbot.chatsession')),
            ],
            options={
                'db_table': 'document_vectors',
                'indexes': [models.Index(fields=['document_type'], name='dv_document_type_idx')],
            },
        ),
    ]
